# Generated by Django 5.1.2 on 2024-10-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='subtitulo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
