# Generated by Django 5.1.2 on 2024-10-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_alter_noticia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='status',
            field=models.CharField(choices=[('AN', 'Em análise'), ('PU', 'Publicado'), ('RM', 'Removido')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
