# Generated by Django 5.1.2 on 2024-10-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_alter_noticia_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='imagem',
            new_name='capa',
        ),
    ]
